#!/bin/sh
### Note: No commands may be executed until after the #PBS lines
### Account information
#PBS -W group_list=dtu_00009 -A dtu_00009
### Job name (comment out the next line to get the name of the script used as the job name)
#PBS -N qsub_PhiX_removal_subset
### Output files (comment out the next 2 lines to get the job name used instead)
#PBS -e $PBS_JOBID.qsub_PhiX_removal_subset.stderr
#PBS -o $PBS_JOBID.qsub_PhiX_removal_subset.stdout
### Only send mail when job is aborted or terminates abnormally
#PBS -m n
### Number of nodes
#PBS -l nodes=1:ppn=4:thinnode
### Memory
#PBS -l mem=10gb
### Requesting time - format is <days>:<hours>:<minutes>:<seconds> (here, 30 days)
#PBS -l walltime=01:00:00:00
##contact incase of event
#PBS -M s182409@student.dtu.dk
#PBS -m ae

# or define specific path
cd /home/projects/dtu_00009/data/chicken_data_TM/Hquality


# >>> conda initialize >>>
__conda_setup="$('/home/projects/dtu_00009/people/majjag/Bin/Programs/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/projects/dtu_00009/people/majjag/Bin/Programs/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/projects/dtu_00009/people/majjag/Bin/Programs/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/projects/dtu_00009/people/majjag/Bin/Programs/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

### Here follows the user commands:
 parallel -j 4 "bbduk.sh in={} out=../NoPhiX/{} ref=../phix174_ill.ref.fa k=31 hdist=1" ::: *.fastq.gz

